branch-defaults:
  main:
    environment: Mystorebackend-env
  staging:
    environment: Mystorebackendstaging-env-1
deploy:
  artifact: dist/mystore-backend.zip
environment-defaults:
  Mystorebackend-env:
    branch: null
    repository: null
  Mystorebackendstaging-env-1:
    branch: null
    repository: null
global:
  application_name: mystorebackend
  default_ec2_keyname: null
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
