version: 2.1
orbs:
  # orbs contain basic recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@4.7.0
  aws-cli: circleci/aws-cli@2.0.3
  eb: circleci/aws-elastic-beanstalk@2.0.1
  browser-tools: circleci/browser-tools@1.2.3
  # different jobs are called later in the workflows sections
jobs:
  build-test-deploy:
    docker:
      # the base image can run most needed actions with orbs
      - image: 'cimg/base:stable'
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - eb/setup
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      # install dependencies for front-end application
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      # install dependencies for back-end application
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
      # build front-end application
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      # build back-end application
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
      # run back-end tests
      - run:
          name: Back-End Tests
          command: |
            npm run backend:test
      - run:
          name: Check browser installation
          command: |
            google-chrome --version
            chromedriver --version
      # run front-end tests
      - run:
          name: Front-End Tests
          command: |
            npm run frontend:test
      # Deploy back-end application artifacts to Elastic Beanstalk
      - run:
          name: Back-End Deploy
          command: |
            npm run backend:deploy
      # Deploy front-end application artifacts to Simple Storage Service
      - run:
          name: Front-End Deploy
          command: |
            npm run frontend:deploy
workflows:
  mystore-workflow:
    jobs:
      - build-test-deploy
